import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 10

[font.bold]
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.offset]
x = 1
y = 1

[[keyboard.bindings]]
chars = "\u001B[70;6u"
key = "F"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[65;5u"
key = "A"
mods = "Control|Shift"

[scrolling]
history = 10000

[shell]
args = ["--login"]
program = "/bin/zsh"

[window]
dynamic_padding = false
dynamic_title = false
opacity = 0.90
startup_mode = "Windowed"

[window.dimensions]
columns = 80
lines = 25

[window.padding]
x = 8
y = 2
