set -g status-justify "left"
set -g status "on"
set -g status-left-style "none"

# Middle section
set -g message-command-style "fg=#083642,bg=#083642"
set -g status-right-style "none"
set -g status-style "none,bg=#083642"

# Active border on pane
set -g pane-active-border-style "fg=#18A7CC"

# When commands are run
set -g message-style "fg=#18A7CC,bg=#083642"

# Separator colors
#setw -g window-status-separator ""
#setw -g window-status-style "none,fg=#686f9a,bg=#30365F"

# Left
set -g status-left "#[fg=#18A7CC,bg=#083642] #S #[fg=#083642,bg=#083642ffffff,nobold,nounderscore,noitalics]"

# Right
set -g status-right "#[fg=#083642,bg=#083642,nobold,nounderscore,noitalics]#[fg=#18A7CC,bg=#083642] %Y-%m-%d  %H:%M #[fg=#18A7CC,bg=#083642,nobold,nounderscore,noitalics]#[fg=#18A7CC,,bg=#083642] #h "
# Inactive window
setw -g window-status-format "#[fg=#18A7CC,bg=#083642] #I #[fg=#258BD2,bg=#083642] #W "

# Active window
setw -g window-status-current-format "#[fg=#083642,bg=#083642,nobold,nounderscore,noitalics]#[fg=#18A7CC,bg=#083642] #I #[fg=#18A7CC,bg=#083642] #W #[fg=#18A7CC,bg=#083642,nobold,nounderscore,noitalics]"
